project:
  type: website
  render: 
    - index.qmd
    - "*.ipynb"
  resources:
    - assets/
  



website:
  title: "liz goodwin"
  navbar:
    left:
      - href: index.qmd
        text: portfolio
      - href: "https://github.com/lizdotsh"
        text: github
      - href: "mailto:work@lizgood.win"
        text: email
      - href: "https://resume.lizgood.win"
        text: resume
 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
search: false


