project:
  type: website
  resources:
    - assets/
  



website:
  title: "Liz Goodwin"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



