project:
  type: website
  render: 
    - index.qmd
    - "*.ipynb"
  resources:
    - assets/
  



website:
  title: "Liz Goodwin"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: "https://github.com/lizdotsh"
        text: Github

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
search: false


